AWSTemplateFormatVersion: "2010-09-09"
Description: A Template to create a bucket for use to store Terraform Remote State
Parameters:
  Environment:
    Type: String
    Default: dev

Resources:
  TfRemoteStateBucket:
    Type: "AWS::S3::Bucket"
    Properties: 
      BucketName: !Sub 'fid-pong-${Environment}-tf-remote-state-${AWS::Region}-bucket'